### PR TITLE
Update test config and TenantFileSystemStorage for #249

### PR DESCRIPTION
**Pull request by atodorov**
First step, this got docker running for me and tests are PASS.

I believe the current file storage class and its tests are wrong and thus causing #249 so this is what I am going to investigate next (and possibly push to the same PR if you don't merge before that).

### CODE REVIEW

**Comment by atodorov** [comment]
@tomturner - with all of these changes I'm able to execute the tests locally and they pass, files are saved under different directories based on the schema_name.

The failure comes from the multiprocessing executor telling me that migration already exists. From what I can tell a tenant already exists in the DB but for some reason we try to create it again. I need a hint on this one.

Another question: do you mind including this and other open PRs in a release after Django 2.2 comes out?

**Comment by tomturner** [comment]
@atodorov regrading PR going in before the next release it depend if it ready in time. I will only merge if passes Travis the test I will look however I am quite busy so other peoples help would be good

**Comment by atodorov** [comment]
> @atodorov regrading PR going in before the next release it depend if it ready in time. I will only merge if passes Travis the test I will look however I am quite busy so other peoples help would be good

+1 here, I'am also quite busy but need some hints how to debug the failure.

It seems to be only related to the multiprocessing executor. Not sure why it is failing. Is it by chance that it is trying to re-use the same database/migrations which already exist ? I'm not even sure what this multiprocessing executor is and why we need it in the tests.

**Comment by alexandernst** [comment]
I'm trying to debug the multiprocessing problem in my branch, but it just seems like there is some major wtf going on. I see migrations being ran multiple times per tenant and per test. 

I'll keep this updated.

**Comment by atodorov** [comment]
Superseded by #255 so closing.

**Pull request closed without merging**
