### PR TITLE
Added docker-based tests

### PR DESCRIPTION
**Pull request by CGenie**
This is to make it easier for developers to set up their local env
for testing.

### CODE REVIEW

**Comment by tomturner** [comment]
@CGenie Can you fixed the test?

**Comment by CGenie** [comment]
Yeah, just need to fix test script since I think I broke it :) With `docker-compose` things are really easy, just install docker and then `pip install docker-compose` and you're done :)

**Comment by tomturner** [comment]
@CGenie Where do I do that?

**Comment by kosz85** [comment]
@CGenie Maybe write some docs :P

**Comment by CGenie** [comment]
What do you mean where? :)

**Comment by CGenie** [comment]
Already added docs to the `README.rst` :)

**Comment by tomturner** [comment]
@CGenie How do I get travis-c to pass do we need to change antyhing?

**Comment by CGenie** [comment]
Yes, I just fixed `run_tests.sh`, just wait a sec it should work now.

**Comment by tomturner** [comment]
@CGenie Thanks for this

**Pull request merged**
