### PR TITLE
added plan options to support django>=2.2

### PR DESCRIPTION
**Pull request by domdinicola**
you could merge it when 2.2 is official released, but the code should be retrocompatible

### CODE REVIEW

**Comment by atodorov** [comment]
@domdinicola maybe you can cherry-pick my commit from #250 so we can have separate testing with 2.2rc1before the official 2.2 release.

**Comment by atodorov** [comment]
@tomturner what are your plans wrt releasing a new version right when Django 2.2 becomes available (which will hopefully be next week) ?

**Comment by tomturner** [comment]
I will wait until it out then I will upgrade. I want it for my project so hopefully within a week of Django 2.2 being released

**Comment by lorinkoz** [comment]
Hi everyone. In Django 2.2, are there any forseeable breaking changes or new features to take advantage of?

**Comment by atodorov** [comment]
@lorinkoz here's what I had to change for Kiwi TCMS: https://github.com/kiwitcms/Kiwi/pull/873

that said there are some backwards incompatible changes in Django 2.2 so make sure to read the release notes and test your app accordingly.

**Comment by tomturner** [comment]
Django 2.2 is now out as of today. Personal I haven't tested this this yet however I want to commit it so other can test it. I will hope to test later this week thanks @domdinicola for the PR

**Pull request merged**
