### PR TITLE
Improved tenant storages and tenant finders to work with any management comands;  Add storage s3boto Fix template loader;  Add solution to ALLOWED_HOSTS to work with the same tenant domain. 

### PR DESCRIPTION
**Pull request by mateuspadua**
Improved tenant storages and tenant finders to work with any management commands.
Add storage s3boto.
Fix Tenant Template Loader.
Add solution to ALLOWED_HOSTS to work with the same tenant domain.
:)

### CODE REVIEW

**Comment by tomturner** [comment]
@mateuspadua I will have a look. First glance you are a lot of commented out code which needs to go before it gets merged

**Comment by mateuspadua** [comment]
Hello @tomturner. Thanks for review. I am going to remove that comments and then i will send new pull request. :)

**Comment by tomturner** [comment]
@mateuspadua Ok i won't merge test / merge until I have that new patch

**Comment by tomturner** [comment]
@mateuspadua Do you think you will do the new patch or do close this pull request

**Comment by mateuspadua** [comment]
Hi, @tomturner, I am closing this PR, cause I will do new PR with new changes and soon I do another PR.

**Comment by tomturner** [comment]
Ok I look forward to the new changes

**Pull request closed without merging**
