### PR TITLE
Update template loaders and static file storage for Django > 2.0 

### LINKED ISSUE #197: MULTITENANT_RELATIVE_STATIC_ROOT not working as intended
According to the [documentation](https://github.com/tomturner/django-tenants/blob/12b6a852236363c8478c944e79b1432f5c0f3c46/docs/static.rst#examples), MULTITENANT_RELATIVE_STATIC_ROOT is supposed to default to ``tenant_name``.

This does not appear to be happening, and neither is ``%s``  resolved to the current schema name when used as part of a dynamic path configuration.

The end result is that a ``django.core.exceptions.SuspiciousFileOperation`` exception is raised.

This was also previously reported in #187 though no solution was provided.

### PR DESCRIPTION
**Pull request by jcass77**
It looks like TenantStaticFileStorage has not been updated since Django 1.8, and is no longer compatible with Django > 2.0. 

This PR just rebases the implementation on the standard django.template.loaders package to bring django-tenants back up to parity.

Fixes #197.

### CODE REVIEW

**Comment by jcass77** [comment]
I think this PR can be cleaned up further to align the implementation more closely with Django > 2.0.

It is currently a work in progress and I should be able to push the final version in the next few days.

**Comment by jcass77** [comment]
Ok, I think this PR is ready for review. It resolves a large number of long-standing issues related to static file handling.

Apologies for the large commit - most of the diffs are generated by documentation changes and new test cases.

- re-based implementation on Django 2.0 static file finders and storage handlers. Fixes #197. Fixes #187.
- static files defined in the tenant folders will now correctly override any project-level files of the same name. This makes it possible to have tenants selectively change just those files (e.g. images, CSS or JavaScript), that are unique to a particular tenant. 
- ``collectstatic_schemas`` now collects the static files to the correct subdirectory for each tenant.
- Added new template loader. Fixes #158.
- got rid of ``CURRENT_SCHEMA_TO_SERVER_STATICFILES`` hack. Fixes #188.
- added test cases for everything related to static file handling.
- added sensible defaults to make configuration easier.
- rewrote the documentation to simplify configuration steps.
- updated travis django dependency to Django>=2.0,<2.2 to align with setup.py. This would cause the travis build to fail with the new implementation. Also addresses #196.
- updated docker image to use ubuntu:16.04 so that we can get access to Python 3.6 for testing.

**Comment by phalt** [comment]
+1 this will resolve the tests, which do not currently pass when running `setup.py` locally

**Comment by tomturner** [comment]
@jcass77 Thanks for this.

**Comment by rdraju** [comment]
django_tenants.template.loaders.filesystem.Loader get initialized only once. It happens with the first request and directories are set based on that tenant. Same template directories get utilized for all further requests from any tenant.

**Comment by rdraju** [comment]
Not relying on self.dirs and overriding get_dirs is the way to go? Any performance considerations? Can they be mitigated using CachedLoader?

**Comment by jcass77** [comment]
Hmmm...I thought I tested that scenario but you are right @rdraju, the Loader is only initialised once so can see how the same template might be returned for all subsequent tenants.

Have a look at ``TenantFileSystemFinder`` for ideas on doing lazy loading so that the dirs are still only initialised once for each tenant.

**Comment by selvara80** [comment]
Unfortunately, This change breaks  other functionalities.
1)STATICFILES_FINDERS  is only looking for static files from the tenant folder. No file is fetched from the public folder.
2)When testing Media, No module named 'django_tenants.files.storages' .Believe the file name incorrectly got changed to 'storage'

**Comment by jcass77** [comment]
1. As far as I can recall, the standard Django finders will take care of looking up static files in the public folder. You still need to reference it in your ``settings.py`` though, which should include something like the following:
```
STATICFILES_FINDERS = [
    # https://django-tenants.readthedocs.io/en/latest/static.html#static-files-finders-aware-tenant
    "django_tenants.staticfiles.finders.TenantFileSystemFinder",  # Must be first
    "django.contrib.staticfiles.finders.FileSystemFinder",  # <-- include Django standard finder.
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
```
2.``django_tenants.files.storages`` was renamed to ``django_tenants.files.storage`` to align more closely with the Django standard naming convention. I updated all of the internal references but might have underestimated the impact that this could have on existing users with pre-existing configurations. Have you tried updating your settings to use the new module name?

**Comment by gnalbandian** [comment]
> 1. As far as I can recall, the standard Django finders will take care of looking up static files in the public folder. You still need to reference it in your `settings.py` though, which should include something like the following:
> 
> ```
> STATICFILES_FINDERS = [
>     # https://django-tenants.readthedocs.io/en/latest/static.html#static-files-finders-aware-tenant
>     "django_tenants.staticfiles.finders.TenantFileSystemFinder",  # Must be first
>     "django.contrib.staticfiles.finders.FileSystemFinder",  # <-- include Django standard finder.
>     "django.contrib.staticfiles.finders.AppDirectoriesFinder",
> ]
> ```
> 2.`django_tenants.files.storages` was renamed to `django_tenants.files.storage` to align more closely with the Django standard naming convention. I updated all of the internal references but might have underestimated the impact that this could have on existing users with pre-existing configurations. Have you tried updating your settings to use the new module name?

The issue seems to be that the {% static %} is always replaced by the STATIC_ROOT path and the schema name of the tenant appended ( STATIC_ROOT/tenant_schema ) even though there is no specific folder for tenant static files

**Comment by jcass77** [comment]
@gnalbandian can you log a ticket so that we can track an resolve this separately.

If there are no tenant-specific static files for the project, then removing it from the ``STATICFILES_FINDERS`` config section and relying on the Django standard ``django.contrib.staticfiles.finders.FileSystemFinder`` should be all that is required for that specific use case - or am I overlooking something else?

**Comment by jcass77** [comment]
Thanks for the feedback @gnalbandian. Yes I think that is the intended behaviour: each ``STATICFILES_FINDERS`` only looks for static files in the specific folders that it has been designed / configured for.

For ``django.contrib.staticfiles.finders.FileSystemFinder``, that means tenant-specific files.

**Pull request merged**
